In [1]:
from numpy import array
from sklearn.decomposition import PCA
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# create the PCA instance
pca = PCA(2)
# fit on data
pca.fit(A)
# access values and vectors
print(pca.components_)
print(pca.explained_variance_)
# transform data
B = pca.transform(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]


In [5]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print('MEAN')
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print('COVARIANCE MATRIX')
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print('VECTORS')
print(vectors)
print('VALUES')
print(values)
# project data
P = vectors.T.dot(C.T)
print('EIGEN VALUES')
print(P.T)


[[1 2]
 [3 4]
 [5 6]]
MEAN
[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
COVARIANCE MATRIX
[[4. 4.]
 [4. 4.]]
VECTORS
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
VALUES
[8. 0.]
EIGEN VALUES
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
